_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.8
            "6": 4.50.1
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
        visualize:
            pretrained-sentiment-gpt2/test/confusion_matrix_plot:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: pretrained-sentiment-gpt2/test/confusion_matrix_plot_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            scratch-sentiment-gpt2/test/confusion_matrix_plot:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: scratch-sentiment-gpt2/test/confusion_matrix_plot_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
